blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, posts_by_category, search_posts

posts_patterns = ([
    path('', PostListView.as_view(), name='post_list'),
    path('<int:post_id>/<slug:page_slug>/', PostDetailView.as_view(), name='post_detail'),
    path('category/<int:category_id>/', posts_by_category, name="posts_by_category"),
    path('search/<value>', search_posts, name="search_posts")
    ], "posts")

core/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.biography, name="biography"),
]

walterini/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.urls import posts_patterns
from portfolio.urls import portfolio_patterns

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    # Home paths
    path('', include('home.urls')),
    # Core paths
    path('core/', include('core.urls')),
    # Paths de posts
    path('blog/', include(posts_patterns)),
    # Paths de contact
    path('contact/', include('contact.urls')),
    # Paths de Portfolio
    path('portfolio/', include(portfolio_patterns)),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Walterini"

core/models.py
from django.db import models
from django.contrib.auth.models import User
from colorfield.fields import ColorField


def custom_skill_upload_to(instance, filename):
    try:
        old_instance = Skill.objects.get(pk=instance.pk)
    except Skill.DoesNotExist:
        old_instance = None
    if old_instance is not None:
        old_instance.image.delete()
    return 'skills/' + filename


def custom_profile_upload_to(instance, filename):
    try:
        old_instance = Profile.objects.get(pk=instance.pk)
    except Profile.DoesNotExist:
        old_instance = None
    if old_instance is not None:
        old_instance.image.delete()
    return 'profiles/' + filename


# Create your models here.
class Skill(models.Model):
    skill_name = models.CharField(verbose_name="Habilidad", max_length=100)
    image = models.ImageField(upload_to=custom_skill_upload_to, verbose_name="Logo")
    color = ColorField(default='#2c98f0', verbose_name="Color del logo")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Habilidad"
        verbose_name_plural = "Habilidades"
        ordering = ['-created']

    def __str__(self):
        return self.skill_name


class Profile(models.Model):
    name = models.CharField(verbose_name="Nombre", max_length=100)
    last_name = models.CharField(verbose_name="Apellidos", max_length=200)
    image = models.ImageField(upload_to=custom_profile_upload_to, verbose_name="Imagen")
    profession = models.CharField(max_length=100, blank=True, verbose_name="Profesión")
    email = models.EmailField(verbose_name="Email", null=True, blank=True)
    address = models.CharField(verbose_name="Dirección", max_length=200, null=True, blank=True)
    mobile = models.CharField(verbose_name="Celular", max_length=15, blank=True, null=True)
    city = models.CharField(max_length=50, verbose_name="Ciudad", blank=True, null=True)
    biography = models.TextField(verbose_name="Biografía")
    skills = models.ManyToManyField(Skill, verbose_name="Habilidades", related_name="get_profiles")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
    isPublished = models.BooleanField(default=False, verbose_name="Publicar", unique=True)

    class Meta:
        verbose_name = "Perfil"
        verbose_name_plural = "Perfiles"
        ordering = ['-created']

    def __str__(self):
        return self.name + " " + self.last_name

portfolio/models.py
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nombre")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Categoría"
        verbose_name_plural = "Categorias"
        ordering = ['-created']

    def __str__(self):
        return self.name


def custom_photography_upload_to(instance, filename):
    try:
        old_instance = Photography.objects.get(pk=instance.pk)
    except Photography.DoesNotExist:
        old_instance = None
    if old_instance is not None:
        old_instance.image.delete()
    return 'photographs/' + filename


class Photography(models.Model):
    title = models.CharField(verbose_name="Título", max_length=100)
    image = models.ImageField(verbose_name="Imagen", upload_to=custom_photography_upload_to)
    categories = models.ManyToManyField(Category, verbose_name="Categorias", related_name="get_photographs")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
    published = models.BooleanField(default=True, verbose_name="Publicar")

    class Meta:
        verbose_name = "Fotografía"
        verbose_name_plural = "Fotografías"
        ordering = ['-created']

    def __str__(self):
        return self.title


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(published=True)


class Poem(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    content = RichTextField(verbose_name="Contenido", config_name='poem', external_plugin_resources=[(
        'lineheight',
        '/static/core/vendor/ckeditor_plugins/lineheight/lineheight/',
        'plugin.js',
    )],)
    categories = models.ManyToManyField(Category, verbose_name="Categorias", related_name="get_poems")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
    published = models.BooleanField(default=True, verbose_name="Publicar")
    objects = models.Manager()
    is_published = PublishedManager()

    class Meta:
        verbose_name = "Poema"
        verbose_name_plural = "Poemas"
        ordering = ['created']

    def __str__(self):
        return self.title


def custom_drawing_upload_to(instance, filename):
    try:
        old_instance = Drawing.objects.get(pk=instance.pk)
    except Drawing.DoesNotExist:
        old_instance = None
    if old_instance is not None:
        old_instance.image.delete()
    return 'drawings/' + filename


class Drawing(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    image = models.ImageField(verbose_name="Imagen", upload_to=custom_drawing_upload_to)
    categories = models.ManyToManyField(Category, verbose_name="Categorias", related_name="get_drawings")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
    published = models.BooleanField(default=True, verbose_name="Publicar")

    class Meta:
        verbose_name = "Dibujo"
        verbose_name_plural = "Dibujos"
        ordering = ['created']

    def __str__(self):
        return self.title

core/views.py
from django.shortcuts import render


# Create your views here.
def biography(request):
    return render(request, "core/biography.html")

core/templates/core/base.html
<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %}{% endblock %} | Walterini</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />

  <!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

    {% load static %}


	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'core/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/magnific-popup.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'core/css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'core/css/bootstrap.css' %}">
	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'core/css/flexslider.css' %}">
	<!-- Flaticons  -->
	<link rel="stylesheet" href="{% static 'core/fonts/flaticon/font/flaticon.css' %}">
	<!-- Owl Carousel -->
	<link rel="stylesheet" href="{% static 'core/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/owl.theme.default.min.css' %}">
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'core/css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'core/js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'core/js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body>
    <div id="colorlib-page">
		<div class="container-wrap">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"><i></i></a>
		<aside id="colorlib-aside" role="complementary" class="border js-fullheight">
			<div class="text-center">
                {% load profiles_extras %}
                {% get_profile as profile %}
                {% if profile %}
                    <div class="author-img" style="background-image: url({{profile.image.url}});"></div>
                    <h1 id="colorlib-logo"><a href="{% url 'biography' %}">{{ profile.name }} {{ profile.last_name }}</a></h1>
                    <span class="position"><a href="#">{{ profile.profession }}</a> en {{ profile.city }}</span>
                {% else %}
                    <div class="author-img" style="background-image: url({% static 'core/images/about.jpg' %});"></div>
                    <h1 id="colorlib-logo"><a href="{% url 'biography' %}">Nombre Apellido</a></h1>
                    <span class="position"><a href="#">Profesión</a> en Ciudad</span>
                {% endif %}
			</div>
			<nav id="colorlib-main-menu" role="navigation" class="navbar">
				<div class="collapse">
					<ul>
						<li class="{% if request.path == '/' %}active{% endif %}"><a href="{% url 'home' %}">Inicio</a></li>
						<li class="{% if request.path == '/core/' %}active{% endif %}"><a href="{% url 'biography' %}">Biografía</a></li>
{#						<li><a href="#" data-nav-section="skills">Skills</a></li>#}
						<li class="{% if request.path|slice:":23" == '/portfolio/photography/' %}active{% endif %}"><a href="{% url 'projects:photography_list' %}">Fotografía</a></li>
						<li class="{% if request.path|slice:":16" == '/portfolio/poem/' %}active{% endif %}"><a href="{% url 'projects:poem_list' %}">Poesía</a></li>
						<li class="{% if request.path|slice:":19" == '/portfolio/drawing/' %}active{% endif %}"><a href="{% url 'projects:drawing_list' %}">Dibujo</a></li>
						<li class="{% if request.path|slice:":6" == '/blog/' %}active{% endif %}"><a href="{% url 'posts:post_list' %}">Blog</a></li>
						<li class="{% if request.path == '/contact/' %}active{% endif %}"><a href="{% url 'contact' %}">Contacto</a></li>
					</ul>
				</div>
			</nav>

			<div class="colorlib-footer">
				<p><small>&copy; <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --> </span> <span>Demo Images: <a href="https://unsplash.com/" target="_blank">Unsplash.com</a></span><span>Developed by: <a href="https://www.facebook.com/luis.pillaga" target="_blank">Luis Pillaga</a></span></small></p>
				<ul>
                    {% if LINK_FACEBOOK %}
                        <li><a href="{{ LINK_FACEBOOK }}"><i class="icon-facebook2" style="color:#999999;"></i></a></li>
                    {% endif %}
                    {% if LINK_TWITTER %}
                        <li><a href="{{ LINK_TWITTER }}"><i class="icon-twitter2" style="color:#999999;"></i></a></li>
                    {% endif %}
                    {% if LINK_INSTAGRAM %}
                        <li><a href="{{ LINK_INSTAGRAM }}"><i class="icon-instagram" style="color:#999999;"></i></a></li>
                    {% endif %}
                    {% if LINK_LINKEDIN %}
                        <li><a href="{{ LINK_LINKEDIN }}"><i class="icon-linkedin2" style="color:#999999;"></i></a></li>
                    {% endif %}
				</ul>
			</div>

		</aside>
            <div id="fb-root"></div>
            <script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v3.2&appId=424505951642710&autoLogAppEvents=1"></script>
		<div id="colorlib-main">
            {% block content %}
            {% endblock%}
		</div><!-- end:colorlib-main -->
	</div><!-- end:container-wrap -->
	</div><!-- end:colorlib-page -->

	<!-- jQuery -->
	<script src="{% static 'core/js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'core/js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'core/js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'core/js/jquery.waypoints.min.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'core/js/jquery.flexslider-min.js' %}"></script>
	<!-- Owl carousel -->
	<script src="{% static 'core/js/owl.carousel.min.js' %}"></script>
	<!-- Counters -->
	<script src="{% static 'core/js/jquery.countTo.js' %}"></script>
	<script src="{% static 'core/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'core/js/main-gallery.js' %}"></script>
	<script src="{% static 'core/js/jquery.ripples-min.js' %}"></script>

	
	<!-- MAIN JS -->
	<script src="{% static 'core/js/main.js' %}"></script>

	</body>
</html>

core/templates/core/biography.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Biografía{% endblock %}
{% block content %}
    <section class="colorlib-about">
        <div class="colorlib-narrow-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="row row-bottom-padded-sm animate-box" data-animate-effect="fadeInLeft">
                        <div class="col-md-12">
                            <div class="about-desc">
                                <span class="heading-meta">Biografía</span>
                                <h2 class="colorlib-heading">¿Quién soy?</h2>
                                {% if profile %}
                                    <p>{{ profile.biography }}</p>
                                {% else %}
                                    <p><strong>Hi I'm Jackson Ford</strong> Este es un texto de prueba. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country.</p>
                                    <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% if profile %}
                            {% for skill in profile.skills.all %}
                                <div class="col-md-3 animate-box" data-animate-effect="fadeInLeft">
                                    <div class="services color-1" style="border-bottom: 2px solid {{ skill.color }};">
                                        <span class="icon2"><img width="37px" height="37px" src="{{ skill.image.url }}"></span>
                                        <h3>{{ skill.skill_name }}</h3>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="col-md-3 animate-box" data-animate-effect="fadeInRight">
                                <div class="services color-2">
                                    <span class="icon2"><i class="icon-globe-outline"></i></span>
                                    <h3>Habilidad de Prueba</h3>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

core/templates/core/photografy.html
<section class="colorlib-work" data-section="work">
    <div class="colorlib-narrow-content">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
                <span class="heading-meta">My Work</span>
                <h2 class="colorlib-heading animate-box">Recent Work</h2>
            </div>
        </div>
        <div class="row row-bottom-padded-sm animate-box" data-animate-effect="fadeInLeft">
            <div class="col-md-12">
                <p class="work-menu"><span><a href="#" class="active">Graphic Design</a></span> <span><a href="#">Web Design</a></span> <span><a href="#">Software</a></span> <span><a href="#">Apps</a></span></p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
                <div class="project" style="background-image: url(images/img-1.jpg);">
                    <div class="desc">
                        <div class="con">
                            <h3><a href="work.html">Work 01</a></h3>
                            <span>Website</span>
                            <p class="icon">
                                <span><a href="#"><i class="icon-share3"></i></a></span>
                                <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 animate-box" data-animate-effect="fadeInRight">
                <div class="project" style="background-image: url(images/img-2.jpg);">
                    <div class="desc">
                        <div class="con">
                            <h3><a href="work.html">Work 02</a></h3>
                            <span>Animation</span>
                            <p class="icon">
                                <span><a href="#"><i class="icon-share3"></i></a></span>
                                <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 animate-box" data-animate-effect="fadeInTop">
                <div class="project" style="background-image: url(images/img-3.jpg);">
                    <div class="desc">
                        <div class="con">
                            <h3><a href="work.html">Work 03</a></h3>
                            <span>Illustration</span>
                            <p class="icon">
                                <span><a href="#"><i class="icon-share3"></i></a></span>
                                <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 animate-box" data-animate-effect="fadeInBottom">
                <div class="project" style="background-image: url(images/img-4.jpg);">
                    <div class="desc">
                        <div class="con">
                            <h3><a href="work.html">Work 04</a></h3>
                            <span>Application</span>
                            <p class="icon">
                                <span><a href="#"><i class="icon-share3"></i></a></span>
                                <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
                <div class="project" style="background-image: url(images/img-5.jpg);">
                    <div class="desc">
                        <div class="con">
                            <h3><a href="work.html">Work 05</a></h3>
                            <span>Graphic, Logo</span>
                            <p class="icon">
                                <span><a href="#"><i class="icon-share3"></i></a></span>
                                <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 animate-box" data-animate-effect="fadeInRight">
                <div class="project" style="background-image: url(images/img-6.jpg);">
                    <div class="desc">
                        <div class="con">
                            <h3><a href="work.html">Work 06</a></h3>
                            <span>Web Design</span>
                            <p class="icon">
                                <span><a href="#"><i class="icon-share3"></i></a></span>
                                <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 animate-box">
                <p><a href="#" class="btn btn-primary btn-lg btn-load-more">Load more <i class="icon-reload"></i></a></p>
            </div>
        </div>
    </div>
</section>

core/templates/core/skill.html
<section class="colorlib-skills" data-section="skills">
    <div class="colorlib-narrow-content">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
                <span class="heading-meta">My Specialty</span>
                <h2 class="colorlib-heading animate-box">My Skills</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 animate-box" data-animate-effect="fadeInLeft">
                <p>The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way.</p>
            </div>
            <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
                <div class="progress-wrap">
                    <h3>Photoshop</h3>
                    <div class="progress">
                        <div class="progress-bar color-1" role="progressbar" aria-valuenow="75"
                             aria-valuemin="0" aria-valuemax="100" style="width:75%">
                            <span>75%</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 animate-box" data-animate-effect="fadeInRight">
                <div class="progress-wrap">
                    <h3>jQuery</h3>
                    <div class="progress">
                        <div class="progress-bar color-2" role="progressbar" aria-valuenow="60"
                             aria-valuemin="0" aria-valuemax="100" style="width:60%">
                            <span>60%</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
                <div class="progress-wrap">
                    <h3>HTML5</h3>
                    <div class="progress">
                        <div class="progress-bar color-3" role="progressbar" aria-valuenow="85"
                             aria-valuemin="0" aria-valuemax="100" style="width:85%">
                            <span>85%</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 animate-box" data-animate-effect="fadeInRight">
                <div class="progress-wrap">
                    <h3>CSS3</h3>
                    <div class="progress">
                        <div class="progress-bar color-4" role="progressbar" aria-valuenow="90"
                             aria-valuemin="0" aria-valuemax="100" style="width:90%">
                            <span>90%</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
                <div class="progress-wrap">
                    <h3>WordPress</h3>
                    <div class="progress">
                        <div class="progress-bar color-5" role="progressbar" aria-valuenow="70"
                             aria-valuemin="0" aria-valuemax="100" style="width:70%">
                            <span>70%</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 animate-box" data-animate-effect="fadeInRight">
                <div class="progress-wrap">
                    <h3>SEO</h3>
                    <div class="progress">
                        <div class="progress-bar color-6" role="progressbar" aria-valuenow="80"
                             aria-valuemin="0" aria-valuemax="100" style="width:80%">
                            <span>80%</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>